openapi: "3.0.0"
info:
  version: 1.0.0
  title: Yaade OpenAPI
  license:
    name: MIT
paths:
  /api/health:
    get:
      summary: Check if the server is running
      operationId: health
      tags:
        - health
      responses:
        '200':
          description: "Success"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HealthResponse"
  /api/collection:
    get:
      summary: Get all collections
      operationId: getAllCollections
      responses:
        '200':
          description: "Success"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Collections"
    post:
      summary: Create a collection
      operationId: postCollection
      requestBody:
        description: A new collection
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateCollectionRequest"
      responses:
        '200':
          description: "Success"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Collection"
    put:
      summary: Update a collection
      operationId: putCollection
      requestBody:
        description: The updated collection
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Collection"
      responses:
        '200':
          description: "Success"
  /api/collection/{id}:
    delete:
      summary: Delete a collection
      operationId: deleteCollection
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
      responses:
        '200':
          description: "Success"
  /api/request:
    post:
      summary: Creata a new request
      operationId: postRequest
      requestBody:
        description: A new request
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateRequestRequest"
      responses:
        '200':
          description: "Success"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Request"
    put:
      summary: Update a request
      operationId: putRequest
      requestBody:
        description: The new request
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Request"
      responses:
        '200':
          description: "Success"
  /api/request/{id}:
    delete:
      summary: Delete a request
      operationId: deleteRequest
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
      responses:
        '200':
          description: "Success"
  /api/login:
    post:
      summary: Login
      operationId: doLogin
      requestBody:
        description: Credentials
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoginRequest"
      responses:
        '200':
          description: "Success"
  /api/logout:
    post:
      summary: Login
      operationId: doLogout
      responses:
        '200':
          description: "Success"
  /api/user:
    get:
      summary: Get the current user
      operationId: getCurrentUser
      responses:
        '200':
          description: "Success"
    put:
      summary: Change user password
      operationId: changeUserPassword
      requestBody:
        description: New and current password
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ChangePasswordRequest"
      responses:
        '200':
          description: "Success"
  /api/user/exportBackup:
    get:
      summary: Export a backup of the database
      operationId: exportBackup
      responses:
        '200':
          description: "Success"
  /api/user/importBackup:
    post:
      summary: Import a backup file
      operationId: importBackup
      responses:
        '200':
          description: "Success"
components:
  schemas:
    HealthResponse:
      type: object
      required:
        - status
        - version
    Request:
      type: object
      required:
        - id
        - collectionId
        - data
      properties:
        id:
          type: integer
          format: int64
        collectionId:
          type: integer
          format: int64
        data:
          type: object
    Collection:
      type: object
      required:
        - id
        - data
      properties:
        id:
          type: integer
          format: int64
        version:
          type: string
        data:
          type: object
    Collections:
      type: array
      items:
        $ref: "#/components/schemas/Collection"

    ########## Requests ##########
    CreateCollectionRequest:
      type: object
      required:
        - name
      properties:
        name:
          type: string
    CreateRequestRequest:
      type: object
      required:
        - collectionId
        - type
      properties:
        collectionId:
          type: integer
          format: int64
        name:
          type: string
        type:
          type: string
    LoginRequest:
      type: object
      required:
        - username
        - password
      properties:
        username:
          type: string
        password:
          type: string
    ChangePasswordRequest:
      type: object
      required:
        - currentPassword
        - newPassword
      properties:
        currentPassword:
          type: string
        newPassword:
          type: string

